// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2Cn5CC6K9ODg3jkiSmEW5dkMEkvBclrM',
    appId: '1:218965503165:web:54523a1cc9556c173e1bd4',
    messagingSenderId: '218965503165',
    projectId: 'offlinereportsystem-d6353',
    authDomain: 'offlinereportsystem-d6353.firebaseapp.com',
    storageBucket: 'offlinereportsystem-d6353.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlYDIM3tSKii3R27sJnCp1JmBvlG4oMiU',
    appId: '1:218965503165:android:d5603a1a443a05703e1bd4',
    messagingSenderId: '218965503165',
    projectId: 'offlinereportsystem-d6353',
    storageBucket: 'offlinereportsystem-d6353.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxv1yCaqTkFcOD9myWzRli-DNmF5SDz00',
    appId: '1:218965503165:ios:fadcfbc4498963983e1bd4',
    messagingSenderId: '218965503165',
    projectId: 'offlinereportsystem-d6353',
    storageBucket: 'offlinereportsystem-d6353.appspot.com',
    iosBundleId: 'com.example.offlineReportSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxv1yCaqTkFcOD9myWzRli-DNmF5SDz00',
    appId: '1:218965503165:ios:b1042782fb4152d03e1bd4',
    messagingSenderId: '218965503165',
    projectId: 'offlinereportsystem-d6353',
    storageBucket: 'offlinereportsystem-d6353.appspot.com',
    iosBundleId: 'com.example.offlineReportSystem.RunnerTests',
  );
}
